services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - backend-db
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  backend:
    image: ghcr.io/tuurkeersebilck/timemanagement-backend:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - data_protection_keys:/home/app/.aspnet/DataProtection-Keys
    env_file: .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    networks:
      - frontend-backend
      - backend-db
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  frontend:
    image: ghcr.io/tuurkeersebilck/timemanagement-frontend:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8090:80"
    networks:
      - frontend-backend
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  db_data:
  data_protection_keys:

networks:
  frontend-backend:
  backend-db:
